/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AdminContactMessagesRouteImport } from './routes/admin.contact-messages'
import { Route as AdminRecentWorksRouteImport } from './routes/admin.recent-works'
import { Route as AdminServiceRequestsRouteImport } from './routes/admin.service-requests'
import { Route as AdminServicesRouteImport } from './routes/admin.services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContactMessagesRoute = AdminContactMessagesRouteImport.update({
  id: '/admin/contact-messages',
  path: '/admin/contact-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecentWorksRoute = AdminRecentWorksRouteImport.update({
  id: '/admin/recent-works',
  path: '/admin/recent-works',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServiceRequestsRoute = AdminServiceRequestsRouteImport.update({
  id: '/admin/service-requests',
  path: '/admin/service-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service': typeof ServiceRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/admin/contact-messages': typeof AdminContactMessagesRoute
  '/admin/recent-works': typeof AdminRecentWorksRoute
  '/admin/service-requests': typeof AdminServiceRequestsRoute
  '/admin/services': typeof AdminServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service': typeof ServiceRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/admin/contact-messages': typeof AdminContactMessagesRoute
  '/admin/recent-works': typeof AdminRecentWorksRoute
  '/admin/service-requests': typeof AdminServiceRequestsRoute
  '/admin/services': typeof AdminServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service': typeof ServiceRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/admin/contact-messages': typeof AdminContactMessagesRoute
  '/admin/recent-works': typeof AdminRecentWorksRoute
  '/admin/service-requests': typeof AdminServiceRequestsRoute
  '/admin/services': typeof AdminServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/service'
    | '/services'
    | '/settings'
    | '/admin/contact-messages'
    | '/admin/recent-works'
    | '/admin/service-requests'
    | '/admin/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/service'
    | '/services'
    | '/settings'
    | '/admin/contact-messages'
    | '/admin/recent-works'
    | '/admin/service-requests'
    | '/admin/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/service'
    | '/services'
    | '/settings'
    | '/admin/contact-messages'
    | '/admin/recent-works'
    | '/admin/service-requests'
    | '/admin/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServiceRoute: typeof ServiceRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  AdminContactMessagesRoute: typeof AdminContactMessagesRoute
  AdminRecentWorksRoute: typeof AdminRecentWorksRoute
  AdminServiceRequestsRoute: typeof AdminServiceRequestsRoute
  AdminServicesRoute: typeof AdminServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contact-messages': {
      id: '/admin/contact-messages'
      path: '/admin/contact-messages'
      fullPath: '/admin/contact-messages'
      preLoaderRoute: typeof AdminContactMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recent-works': {
      id: '/admin/recent-works'
      path: '/admin/recent-works'
      fullPath: '/admin/recent-works'
      preLoaderRoute: typeof AdminRecentWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/service-requests': {
      id: '/admin/service-requests'
      path: '/admin/service-requests'
      fullPath: '/admin/service-requests'
      preLoaderRoute: typeof AdminServiceRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServiceRoute: ServiceRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  AdminContactMessagesRoute: AdminContactMessagesRoute,
  AdminRecentWorksRoute: AdminRecentWorksRoute,
  AdminServiceRequestsRoute: AdminServiceRequestsRoute,
  AdminServicesRoute: AdminServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
